import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const ADMIN_ID = 'cmp0n2fdp00004o8pe4vfh9nv';
const SCRAPE_RUN_ID = 'cmp0q6mad0002zu0rglu367bw';
const leads = [
    // ===== TIER 1 ELITE =====
    {
        name: 'Khalid Al Mansouri',
        nameAr: 'خالد المنصوري',
        company: 'Al Mansouri Family Office',
        companyAr: 'مكتب عائلة المنصوري',
        role: 'Principal Investor',
        roleAr: 'مستثمر رئيسي',
        source: 'ADGM Registry',
        tier: 1,
        phone: '+971501234567',
        email: 'k.almansouri@mansourifo.ae',
        location: 'Abu Dhabi',
        score: 97,
        signals: ['UHNW', 'Family Office', 'High Net Worth'],
        propertyPref: { types: ['penthouse', 'villa'], bedrooms: '5+' },
        budgetMin: 15000000,
        budgetMax: 50000000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Rashed Al Nuaimi',
        nameAr: 'راشد النعيمي',
        company: 'Gulf Capital Partners',
        companyAr: 'شركاء الخليج للاستثمار',
        role: 'Managing Director',
        roleAr: 'المدير العام',
        source: 'DIFC Registry',
        tier: 1,
        phone: '+971502345678',
        email: 'rashed@gulfcapitalpartners.ae',
        location: 'Dubai',
        score: 96,
        signals: ['UHNW', 'Private Client', 'Investor'],
        propertyPref: { types: ['penthouse', 'apartment'], bedrooms: '4+' },
        budgetMin: 12000000,
        budgetMax: 35000000,
        relocated: false,
        rentalFlag: false,
        status: 'contacted',
    },
    {
        name: 'Anastasia Volkov',
        nameAr: 'أناستاسيا فولكوف',
        company: 'Volkov International Holdings',
        companyAr: 'فولكوف إنترناشيونال القابضة',
        role: 'CEO',
        roleAr: 'الرئيس التنفيذي',
        source: 'Private Banking Directory',
        tier: 1,
        phone: '+971503456789',
        email: 'a.volkov@volkovholdings.com',
        location: 'Dubai',
        score: 95,
        signals: ['UHNW', 'Recently Relocated', 'High Net Worth'],
        propertyPref: { types: ['villa', 'penthouse'], bedrooms: '6+' },
        budgetMin: 20000000,
        budgetMax: 80000000,
        relocated: true,
        rentalFlag: false,
        status: 'qualified',
    },
    {
        name: 'Ahmed bin Saeed Al Rashidi',
        nameAr: 'أحمد بن سعيد الراشدي',
        company: 'Al Rashidi Group',
        companyAr: 'مجموعة الراشدي',
        role: 'Chairman',
        roleAr: 'رئيس مجلس الإدارة',
        source: 'DED Registry',
        tier: 1,
        phone: '+971504567890',
        email: 'ahmed@alrashidigroup.ae',
        location: 'Sharjah',
        score: 94,
        signals: ['UHNW', 'Business Owner', 'Investor'],
        propertyPref: { types: ['villa', 'townhouse'], bedrooms: '5+' },
        budgetMin: 8000000,
        budgetMax: 25000000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Marcus Weber',
        nameAr: 'ماركوس ويبر',
        company: 'Weber Asset Management',
        companyAr: 'ويبر لإدارة الأصول',
        role: 'Founding Partner',
        roleAr: 'الشريك المؤسس',
        source: 'Private Banking Directory',
        tier: 1,
        phone: '+971505678901',
        email: 'm.weber@weberassets.com',
        location: 'Dubai',
        score: 93,
        signals: ['UHNW', 'High Net Worth', 'Recently Relocated'],
        propertyPref: { types: ['penthouse', 'apartment'], bedrooms: '4+' },
        budgetMin: 18000000,
        budgetMax: 60000000,
        relocated: true,
        rentalFlag: false,
        status: 'proposal',
    },
    {
        name: 'Fatima Al Zaabi',
        nameAr: 'فاطمة الزعابي',
        company: 'Al Zaabi Family Investments',
        companyAr: 'استثمارات عائلة الزعابي',
        role: 'Investment Director',
        roleAr: 'مدير الاستثمار',
        source: 'ADGM Registry',
        tier: 1,
        phone: '+971506789012',
        email: 'fatima@alzaabiinvest.ae',
        location: 'Abu Dhabi',
        score: 92,
        signals: ['High Net Worth', 'Private Client', 'Investor'],
        propertyPref: { types: ['villa', 'penthouse'], bedrooms: '5+' },
        budgetMin: 10000000,
        budgetMax: 40000000,
        relocated: false,
        rentalFlag: false,
        status: 'contacted',
    },
    // ===== TIER 2 PREMIUM =====
    {
        name: 'Raj Mehta',
        nameAr: 'راج ميهتا',
        company: 'IndoGulf Trading LLC',
        companyAr: 'هندو خليج للتجارة',
        role: 'Director',
        roleAr: 'مدير',
        source: 'Forbes ME',
        tier: 2,
        phone: '+971507890123',
        email: 'raj.mehta@indogulf.com',
        location: 'Dubai',
        score: 83,
        signals: ['High Net Worth', 'Business Owner', 'Investor'],
        propertyPref: { types: ['apartment', 'penthouse'], bedrooms: '3+' },
        budgetMin: 3000000,
        budgetMax: 10000000,
        relocated: true,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Layla Hassan',
        nameAr: 'ليلى حسن',
        company: 'Zawya Capital',
        companyAr: 'زاوية كابيتال',
        role: 'Portfolio Manager',
        roleAr: 'مدير محفظة',
        source: 'Zawya Invest',
        tier: 2,
        phone: '+971508901234',
        email: 'l.hassan@zawya-capital.com',
        location: 'Dubai',
        score: 81,
        signals: ['Investor', 'High Net Worth'],
        propertyPref: { types: ['apartment', 'villa'], bedrooms: '3+' },
        budgetMin: 2500000,
        budgetMax: 8000000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Dmitri Sokolov',
        nameAr: 'ديمتري سوكولوف',
        company: 'Sokolov Enterprises FZCO',
        companyAr: 'سوكولوف إنتربرايزس',
        role: 'Managing Partner',
        roleAr: 'الشريك الإداري',
        source: 'Bloomberg MENA',
        tier: 2,
        phone: '+971509012345',
        email: 'd.sokolov@sokolov.ae',
        location: 'Dubai',
        score: 79,
        signals: ['High Net Worth', 'Recently Relocated', 'Business Owner'],
        propertyPref: { types: ['villa', 'townhouse'], bedrooms: '4+' },
        budgetMin: 5000000,
        budgetMax: 15000000,
        relocated: true,
        rentalFlag: false,
        status: 'qualified',
    },
    {
        name: 'Sarah Al Khateeb',
        nameAr: 'سارة الخطيب',
        company: 'Concierge Elite Dubai',
        companyAr: 'كونسيرج إيليت دبي',
        role: 'Senior Client Advisor',
        roleAr: 'مستشار عملاء أول',
        source: 'Elite Lifestyle & Concierge',
        tier: 2,
        phone: '+971500123456',
        email: 's.alkhateeb@eliteconcierge.ae',
        location: 'Dubai',
        score: 78,
        signals: ['Private Client', 'High Net Worth'],
        propertyPref: { types: ['apartment', 'penthouse'], bedrooms: '2+' },
        budgetMin: 2000000,
        budgetMax: 7000000,
        relocated: false,
        rentalFlag: false,
        status: 'contacted',
    },
    {
        name: 'Tariq Al Falasi',
        nameAr: 'طارق الفلاسي',
        company: 'Falasi Holdings',
        companyAr: 'هولدينغ الفلاسي',
        role: 'Owner',
        roleAr: 'المالك',
        source: 'Forbes ME',
        tier: 2,
        phone: '+971551234567',
        email: 'tariq@falasihg.ae',
        location: 'Ras Al Khaimah',
        score: 76,
        signals: ['Business Owner', 'Investor'],
        propertyPref: { types: ['villa'], bedrooms: '5+' },
        budgetMin: 4000000,
        budgetMax: 12000000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Priya Nambiar',
        nameAr: 'بريا نامبيار',
        company: 'NRI Investments LLC',
        companyAr: 'مجموعة NRI للاستثمار',
        role: 'Managing Director',
        roleAr: 'المدير الإداري',
        source: 'Zawya Invest',
        tier: 2,
        phone: '+971552345678',
        email: 'p.nambiar@nriinvest.com',
        location: 'Abu Dhabi',
        score: 75,
        signals: ['Investor', 'Recently Relocated', 'High Net Worth'],
        propertyPref: { types: ['apartment', 'villa'], bedrooms: '3+' },
        budgetMin: 3500000,
        budgetMax: 9000000,
        relocated: true,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Omar Al Suwaidi',
        nameAr: 'عمر السويدي',
        company: 'Suwaidi Real Estate Group',
        companyAr: 'مجموعة السويدي العقارية',
        role: 'CEO',
        roleAr: 'الرئيس التنفيذي',
        source: 'Bloomberg MENA',
        tier: 2,
        phone: '+971553456789',
        email: 'omar@suwaidireg.ae',
        location: 'Abu Dhabi',
        score: 77,
        signals: ['Business Owner', 'Investor', 'High Net Worth'],
        propertyPref: { types: ['villa', 'commercial'], bedrooms: '6+' },
        budgetMin: 6000000,
        budgetMax: 20000000,
        relocated: false,
        rentalFlag: false,
        status: 'proposal',
    },
    {
        name: 'Jing Wei Chen',
        nameAr: 'جينغ وي تشن',
        company: 'Sino Gulf Trade Partners',
        companyAr: 'شركاء التجارة الخليجية الصينية',
        role: 'Regional Director',
        roleAr: 'المدير الإقليمي',
        source: 'Forbes ME',
        tier: 2,
        phone: '+971554567890',
        email: 'jw.chen@sinogulf.com',
        location: 'Dubai',
        score: 74,
        signals: ['High Net Worth', 'Recently Relocated', 'Business Owner'],
        propertyPref: { types: ['penthouse', 'apartment'], bedrooms: '4+' },
        budgetMin: 4500000,
        budgetMax: 15000000,
        relocated: true,
        rentalFlag: false,
        status: 'new',
    },
    // ===== TIER 3 STANDARD =====
    {
        name: 'Mohammed Al Habsi',
        nameAr: 'محمد الحبسي',
        company: 'Al Habsi Contracting',
        companyAr: 'شركة الحبسي للمقاولات',
        role: 'General Manager',
        roleAr: 'المدير العام',
        source: 'Bayut',
        tier: 3,
        phone: '+971555678901',
        email: 'm.alhabsi@habsicontracting.ae',
        location: 'Fujairah',
        score: 62,
        signals: ['Business Owner', 'Executive'],
        propertyPref: { types: ['villa', 'townhouse'], bedrooms: '4+' },
        budgetMin: 1500000,
        budgetMax: 4000000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Valentina Rossi',
        nameAr: 'فالنتينا روسي',
        company: 'Italian Chamber of Commerce UAE',
        companyAr: 'الغرفة الإيطالية للتجارة في الإمارات',
        role: 'Executive',
        roleAr: 'تنفيذي',
        source: 'Dubizzle',
        tier: 3,
        phone: '+971556789012',
        email: 'v.rossi@iccuae.com',
        location: 'Dubai',
        score: 61,
        signals: ['Executive', 'Recently Relocated'],
        propertyPref: { types: ['apartment'], bedrooms: '2+' },
        budgetMin: 1200000,
        budgetMax: 3500000,
        relocated: true,
        rentalFlag: false,
        status: 'contacted',
    },
    {
        name: 'Hassan Al Marzouqi',
        nameAr: 'حسن المرزوقي',
        company: 'Marzouqi Trading Est.',
        companyAr: 'مؤسسة المرزوقي التجارية',
        role: 'Owner',
        roleAr: 'المالك',
        source: 'Business Directory UAE',
        tier: 3,
        phone: '+971557890123',
        email: 'hassan@marzouqitrading.ae',
        location: 'Ajman',
        score: 58,
        signals: ['Business Owner'],
        propertyPref: { types: ['townhouse', 'villa'], bedrooms: '3+' },
        budgetMin: 900000,
        budgetMax: 2500000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Nina Petrova',
        nameAr: 'نينا بيتروفا',
        company: 'Freelance Consultant',
        companyAr: 'مستشارة مستقلة',
        role: 'Senior Consultant',
        roleAr: 'مستشارة أولى',
        source: 'Bayut',
        tier: 3,
        phone: '+971558901234',
        email: 'nina.petrova@gmail.com',
        location: 'Dubai',
        score: 55,
        signals: ['Recently Relocated'],
        propertyPref: { types: ['apartment'], bedrooms: '1+' },
        budgetMin: 800000,
        budgetMax: 2000000,
        relocated: true,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Yousef Al Blooshi',
        nameAr: 'يوسف البلوشي',
        company: 'Emirates Technical Services',
        companyAr: 'الإمارات للخدمات التقنية',
        role: 'Operations Manager',
        roleAr: 'مدير العمليات',
        source: 'News & Press',
        tier: 3,
        phone: '+971559012345',
        email: 'y.alblooshi@ets.ae',
        location: 'Sharjah',
        score: 57,
        signals: ['Executive', 'Business Owner'],
        propertyPref: { types: ['apartment', 'townhouse'], bedrooms: '3+' },
        budgetMin: 1000000,
        budgetMax: 3000000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Amira Al Qubaisi',
        nameAr: 'أميرة القبيسي',
        company: 'Abu Dhabi Media',
        companyAr: 'أبوظبي للإعلام',
        role: 'Senior Producer',
        roleAr: 'منتجة أولى',
        source: 'Dubizzle',
        tier: 3,
        phone: '+971550123456',
        email: 'amira.alqubaisi@adm.ae',
        location: 'Abu Dhabi',
        score: 53,
        signals: ['Executive'],
        propertyPref: { types: ['apartment'], bedrooms: '2+' },
        budgetMin: 900000,
        budgetMax: 2500000,
        relocated: false,
        rentalFlag: false,
        status: 'contacted',
    },
    {
        name: 'David Okonkwo',
        nameAr: 'ديفيد أوكونكوو',
        company: 'AfricaGulf Business Hub',
        companyAr: 'أفريكا خليج للأعمال',
        role: 'Co-Founder',
        roleAr: 'المؤسس المشارك',
        source: 'Business Directory UAE',
        tier: 3,
        phone: '+971561234567',
        email: 'd.okonkwo@africagulf.com',
        location: 'Dubai',
        score: 60,
        signals: ['Business Owner', 'Recently Relocated'],
        propertyPref: { types: ['apartment', 'commercial'], bedrooms: '2+' },
        budgetMin: 1100000,
        budgetMax: 3200000,
        relocated: true,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Saeed Al Ketbi',
        nameAr: 'سعيد الكتبي',
        company: 'Al Ketbi Automotive Group',
        companyAr: 'مجموعة الكتبي للسيارات',
        role: 'Managing Director',
        roleAr: 'المدير الإداري',
        source: 'Bayut',
        tier: 3,
        phone: '+971562345678',
        email: 'saeed@alketbiautomotive.ae',
        location: 'Umm Al Quwain',
        score: 56,
        signals: ['Business Owner'],
        propertyPref: { types: ['villa'], bedrooms: '4+' },
        budgetMin: 1800000,
        budgetMax: 4500000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Elena Stavros',
        nameAr: 'إيلينا ستافروس',
        company: 'MedArabia Trade LLC',
        companyAr: 'ميد عربيا للتجارة',
        role: 'Commercial Director',
        roleAr: 'المدير التجاري',
        source: 'News & Press',
        tier: 3,
        phone: '+971563456789',
        email: 'elena.stavros@medarabia.com',
        location: 'Dubai',
        score: 59,
        signals: ['Executive', 'Recently Relocated'],
        propertyPref: { types: ['apartment', 'penthouse'], bedrooms: '3+' },
        budgetMin: 2000000,
        budgetMax: 5500000,
        relocated: true,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Khalifa Al Hammadi',
        nameAr: 'خليفة الحمادي',
        company: 'Hammadi Industries',
        companyAr: 'مصانع الحمادي',
        role: 'President',
        roleAr: 'الرئيس',
        source: 'Dubizzle',
        tier: 3,
        phone: '+971564567890',
        email: 'khalifa@hammadiindustries.ae',
        location: 'Ras Al Khaimah',
        score: 63,
        signals: ['Business Owner', 'Executive'],
        propertyPref: { types: ['villa', 'townhouse'], bedrooms: '5+' },
        budgetMin: 2500000,
        budgetMax: 6000000,
        relocated: false,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Nadia Yusupova',
        nameAr: 'ناديا يوسوبوفا',
        company: 'Central Asia UAE Trade Bridge',
        companyAr: 'جسر التجارة بين آسيا الوسطى والإمارات',
        role: 'Director',
        roleAr: 'مدير',
        source: 'Business Directory UAE',
        tier: 3,
        phone: '+971565678901',
        email: 'n.yusupova@cautb.ae',
        location: 'Dubai',
        score: 54,
        signals: ['Recently Relocated', 'Business Owner'],
        propertyPref: { types: ['apartment'], bedrooms: '2+' },
        budgetMin: 700000,
        budgetMax: 2000000,
        relocated: true,
        rentalFlag: false,
        status: 'new',
    },
    {
        name: 'Hamad Al Marri',
        nameAr: 'حمد المري',
        company: 'Al Marri Logistics',
        companyAr: 'المري للخدمات اللوجستية',
        role: 'Operations Director',
        roleAr: 'مدير العمليات',
        source: 'Bayut',
        tier: 3,
        phone: '+971566789012',
        email: 'hamad@almarrilogistics.ae',
        location: 'Dubai',
        score: 61,
        signals: ['Business Owner', 'Executive'],
        propertyPref: { types: ['townhouse', 'villa'], bedrooms: '4+' },
        budgetMin: 1600000,
        budgetMax: 4000000,
        relocated: false,
        rentalFlag: false,
        status: 'closed',
    },
    {
        name: 'Santiago Morales',
        nameAr: 'سانتياغو مورالس',
        company: 'IberArabia Investments',
        companyAr: 'إيبر عربيا للاستثمار',
        role: 'Chief Investment Officer',
        roleAr: 'مدير الاستثمار',
        source: 'News & Press',
        tier: 3,
        phone: '+971567890123',
        email: 's.morales@iberarabia.com',
        location: 'Abu Dhabi',
        score: 65,
        signals: ['Investor', 'Recently Relocated', 'High Net Worth'],
        propertyPref: { types: ['villa', 'penthouse'], bedrooms: '4+' },
        budgetMin: 3500000,
        budgetMax: 10000000,
        relocated: true,
        rentalFlag: false,
        status: 'qualified',
    },
];
async function main() {
    console.log('🌱 Starting seed...');
    // Update the scrape run status
    await prisma.scrapeRun.update({
        where: { id: SCRAPE_RUN_ID },
        data: { status: 'COMPLETED', leadsFound: leads.length, completedAt: new Date() },
    });
    // Seed all leads
    let created = 0;
    for (const lead of leads) {
        await prisma.lead.create({
            data: {
                name: lead.name,
                nameAr: lead.nameAr,
                company: lead.company,
                companyAr: lead.companyAr,
                role: lead.role,
                roleAr: lead.roleAr,
                source: lead.source,
                tier: lead.tier,
                phone: lead.phone,
                email: lead.email,
                location: lead.location,
                score: lead.score,
                signals: lead.signals,
                propertyPref: lead.propertyPref,
                budgetMin: lead.budgetMin,
                budgetMax: lead.budgetMax,
                relocated: lead.relocated,
                rentalFlag: lead.rentalFlag,
                status: lead.status,
                agentId: ADMIN_ID,
                scrapeRunId: SCRAPE_RUN_ID,
            },
        });
        created++;
        process.stdout.write(`  ✓ Created lead ${created}/${leads.length}: ${lead.name}\n`);
    }
    console.log(`\n✅ Seed complete! Created ${created} leads.`);
}
main()
    .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
})
    .finally(async () => {
    await prisma.$disconnect();
});
